export type Category =
  | "infra"
  | "residential"
  | "commercial"
  | "industrial"
  | "civic"
  | "utility"
  | "service"
  | "landmark";

export interface BuildingDef {
  id: string;
  name: string;
  category: Category;
  cost: number;
  upkeep: number;
  description: string;
  icon: string;
  residents: number;
  jobs: number;
  powerUse: number;
  waterUse: number;
  powerGen: number;
  waterGen: number;
  pollution: number;
  serviceRadius: number;
  parkValue: number;
  unique?: boolean;
  isRoad?: boolean;
  color: number;
  height: number;
  unlockPop: number;
}

export const CATALOG: BuildingDef[] = [
  {
    id: "road",
    name: "Avenue",
    category: "infra",
    cost: 25,
    upkeep: 1,
    description: "Connects the city. Buildings need road access to operate.",
    icon: "icon-road.png",
    residents: 0,
    jobs: 0,
    powerUse: 0,
    waterUse: 0,
    powerGen: 0,
    waterGen: 0,
    pollution: 0,
    serviceRadius: 0,
    parkValue: 0,
    isRoad: true,
    color: 0x2a2d33,
    height: 0.06,
    unlockPop: 0,
  },
  {
    id: "cottage",
    name: "Cottage",
    category: "residential",
    cost: 220,
    upkeep: 4,
    description: "A sunlit family home. Modest density, high happiness.",
    icon: "icon-residential.png",
    residents: 8,
    jobs: 0,
    powerUse: 2,
    waterUse: 2,
    powerGen: 0,
    waterGen: 0,
    pollution: 0,
    serviceRadius: 0,
    parkValue: 1,
    color: 0xc4a574,
    height: 0.85,
    unlockPop: 0,
  },
  {
    id: "villa",
    name: "Villa",
    category: "residential",
    cost: 900,
    upkeep: 12,
    description: "Garden estates for affluent citizens.",
    icon: "icon-residential.png",
    residents: 18,
    jobs: 0,
    powerUse: 4,
    waterUse: 4,
    powerGen: 0,
    waterGen: 0,
    pollution: 0,
    serviceRadius: 0,
    parkValue: 2,
    color: 0xd8c4a0,
    height: 1.15,
    unlockPop: 40,
  },
  {
    id: "apartments",
    name: "Apartments",
    category: "residential",
    cost: 2800,
    upkeep: 28,
    description: "Mid-rise living for a growing downtown.",
    icon: "icon-residential.png",
    residents: 60,
    jobs: 0,
    powerUse: 10,
    waterUse: 10,
    powerGen: 0,
    waterGen: 0,
    pollution: 1,
    serviceRadius: 0,
    parkValue: 0,
    color: 0x8d6b4a,
    height: 3.4,
    unlockPop: 120,
  },
  {
    id: "tower",
    name: "Sky Tower",
    category: "residential",
    cost: 14000,
    upkeep: 90,
    description: "A glass spire that defines the skyline.",
    icon: "icon-residential.png",
    residents: 180,
    jobs: 8,
    powerUse: 28,
    waterUse: 24,
    powerGen: 0,
    waterGen: 0,
    pollution: 2,
    serviceRadius: 0,
    parkValue: 0,
    color: 0x6f8c9a,
    height: 9.5,
    unlockPop: 400,
  },
  {
    id: "shop",
    name: "Boutique",
    category: "commercial",
    cost: 420,
    upkeep: 8,
    description: "Storefronts that pay taxes and need shoppers.",
    icon: "icon-commercial.png",
    residents: 0,
    jobs: 10,
    powerUse: 3,
    waterUse: 2,
    powerGen: 0,
    waterGen: 0,
    pollution: 0,
    serviceRadius: 0,
    parkValue: 0,
    color: 0xc45c4a,
    height: 1.05,
    unlockPop: 0,
  },
  {
    id: "market",
    name: "Galleria",
    category: "commercial",
    cost: 2200,
    upkeep: 32,
    description: "A covered market that draws crowds.",
    icon: "icon-commercial.png",
    residents: 0,
    jobs: 36,
    powerUse: 9,
    waterUse: 6,
    powerGen: 0,
    waterGen: 0,
    pollution: 1,
    serviceRadius: 0,
    parkValue: 0,
    color: 0xd4a017,
    height: 1.8,
    unlockPop: 80,
  },
  {
    id: "offices",
    name: "Offices",
    category: "commercial",
    cost: 7200,
    upkeep: 70,
    description: "Corporate floors with a glass curtain wall.",
    icon: "icon-commercial.png",
    residents: 0,
    jobs: 90,
    powerUse: 18,
    waterUse: 8,
    powerGen: 0,
    waterGen: 0,
    pollution: 1,
    serviceRadius: 0,
    parkValue: 0,
    color: 0x4a6d7c,
    height: 5.2,
    unlockPop: 250,
  },
  {
    id: "workshop",
    name: "Workshop",
    category: "industrial",
    cost: 480,
    upkeep: 10,
    description: "Light industry and crafts. Mild smoke.",
    icon: "icon-industrial.png",
    residents: 0,
    jobs: 14,
    powerUse: 6,
    waterUse: 3,
    powerGen: 0,
    waterGen: 0,
    pollution: 4,
    serviceRadius: 0,
    parkValue: 0,
    color: 0x6b5a4a,
    height: 1.2,
    unlockPop: 0,
  },
  {
    id: "factory",
    name: "Factory",
    category: "industrial",
    cost: 3200,
    upkeep: 40,
    description: "Heavy production. Keep parks and homes upwind.",
    icon: "icon-industrial.png",
    residents: 0,
    jobs: 48,
    powerUse: 16,
    waterUse: 8,
    powerGen: 0,
    waterGen: 0,
    pollution: 10,
    serviceRadius: 0,
    parkValue: 0,
    color: 0x5a5348,
    height: 2.2,
    unlockPop: 100,
  },
  {
    id: "plant",
    name: "Foundry",
    category: "industrial",
    cost: 9800,
    upkeep: 85,
    description: "A vast works that employs hundreds.",
    icon: "icon-industrial.png",
    residents: 0,
    jobs: 110,
    powerUse: 30,
    waterUse: 14,
    powerGen: 0,
    waterGen: 0,
    pollution: 18,
    serviceRadius: 0,
    parkValue: 0,
    color: 0x4a433c,
    height: 3.1,
    unlockPop: 350,
  },
  {
    id: "park",
    name: "Park",
    category: "civic",
    cost: 320,
    upkeep: 6,
    description: "Trees and lawns that lift nearby happiness.",
    icon: "icon-park.png",
    residents: 0,
    jobs: 2,
    powerUse: 1,
    waterUse: 2,
    powerGen: 0,
    waterGen: 0,
    pollution: -6,
    serviceRadius: 4,
    parkValue: 8,
    color: 0x3d7a4a,
    height: 0.4,
    unlockPop: 0,
  },
  {
    id: "plaza",
    name: "Grand Plaza",
    category: "civic",
    cost: 1800,
    upkeep: 18,
    description: "A civic square with a fountain and evening lights.",
    icon: "icon-park.png",
    residents: 0,
    jobs: 4,
    powerUse: 3,
    waterUse: 3,
    powerGen: 0,
    waterGen: 0,
    pollution: -8,
    serviceRadius: 6,
    parkValue: 14,
    color: 0xc9b896,
    height: 0.55,
    unlockPop: 150,
  },
  {
    id: "power",
    name: "Power Plant",
    category: "utility",
    cost: 4500,
    upkeep: 55,
    description: "Feeds electricity along roads and adjacent blocks.",
    icon: "icon-power.png",
    residents: 0,
    jobs: 12,
    powerUse: 0,
    waterUse: 4,
    powerGen: 160,
    waterGen: 0,
    pollution: 8,
    serviceRadius: 0,
    parkValue: 0,
    color: 0x2f6d6a,
    height: 2.6,
    unlockPop: 0,
  },
  {
    id: "water",
    name: "Water Tower",
    category: "utility",
    cost: 2800,
    upkeep: 30,
    description: "Pressurizes clean water through the street grid.",
    icon: "icon-water.png",
    residents: 0,
    jobs: 6,
    powerUse: 4,
    waterUse: 0,
    powerGen: 0,
    waterGen: 140,
    pollution: 0,
    serviceRadius: 0,
    parkValue: 0,
    color: 0x3d6d88,
    height: 3.4,
    unlockPop: 0,
  },
  {
    id: "police",
    name: "Constabulary",
    category: "service",
    cost: 3600,
    upkeep: 48,
    description: "Keeps nearby districts safe and orderly.",
    icon: "icon-police.png",
    residents: 0,
    jobs: 16,
    powerUse: 6,
    waterUse: 3,
    powerGen: 0,
    waterGen: 0,
    pollution: 0,
    serviceRadius: 8,
    parkValue: 0,
    color: 0x2c3d5a,
    height: 1.7,
    unlockPop: 60,
  },
  {
    id: "fire",
    name: "Fire Hall",
    category: "service",
    cost: 3400,
    upkeep: 46,
    description: "Protects surrounding blocks from disaster.",
    icon: "icon-fire.png",
    residents: 0,
    jobs: 14,
    powerUse: 5,
    waterUse: 6,
    powerGen: 0,
    waterGen: 0,
    pollution: 0,
    serviceRadius: 8,
    parkValue: 0,
    color: 0x8b2e2e,
    height: 1.6,
    unlockPop: 60,
  },
  {
    id: "hospital",
    name: "Infirmary",
    category: "service",
    cost: 5200,
    upkeep: 70,
    description: "Hospitals raise health and attract families.",
    icon: "icon-hospital.png",
    residents: 0,
    jobs: 22,
    powerUse: 10,
    waterUse: 8,
    powerGen: 0,
    waterGen: 0,
    pollution: 0,
    serviceRadius: 9,
    parkValue: 1,
    color: 0xdfe7ea,
    height: 2.1,
    unlockPop: 90,
  },
  {
    id: "cityhall",
    name: "City Hall",
    category: "landmark",
    cost: 16000,
    upkeep: 80,
    description: "The civic heart. Only one may stand. Boosts prestige.",
    icon: "icon-cityhall.png",
    residents: 0,
    jobs: 20,
    powerUse: 8,
    waterUse: 6,
    powerGen: 0,
    waterGen: 0,
    pollution: 0,
    serviceRadius: 12,
    parkValue: 6,
    unique: true,
    color: 0xc9a227,
    height: 3.8,
    unlockPop: 30,
  },
];

export const CATALOG_BY_ID: Record<string, BuildingDef> = Object.fromEntries(
  CATALOG.map((b) => [b.id, b]),
);

export const TOOL_ORDER = [
  "inspect",
  "road",
  "cottage",
  "villa",
  "apartments",
  "tower",
  "shop",
  "market",
  "offices",
  "workshop",
  "factory",
  "plant",
  "park",
  "plaza",
  "power",
  "water",
  "police",
  "fire",
  "hospital",
  "cityhall",
  "bulldoze",
] as const;

export type ToolId = (typeof TOOL_ORDER)[number];

export function isWaterTile(x: number, y: number, size: number): boolean {
  const nx = x / Math.max(1, size - 1);
  const ny = y / Math.max(1, size - 1);
  const river = Math.abs(ny - (0.44 + 0.11 * Math.sin(nx * Math.PI * 2.15))) < 0.048;
  const lake = (x - size * 0.78) ** 2 + (y - size * 0.2) ** 2 < (size * 0.085) ** 2;
  return river || lake;
}
